version: "3"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    ports: 
      - "3000:80"
    networks:
      - internal
    volumes:
      - ./html/:/var/www/html/
      - ./docker/nginx/logs:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./html/:/var/www/html/
      - ./docker/php/logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/db-data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge